Add missing '-race' flag to go build for race rpm
project-flotta/flotta-device-worker pull request #182
Opened 2022-06-23 19:34 UTC by jordigilh

Added `-race` to the `go build` command to build the race rpm with the race flag enabled.

2022-06-23 20:11 UTC, eloycoto commented on flotta-agent.spec
> +export CGO_ENABLED=1
that's bad, all will have CGO_ENABLED, that need to be changed.

2022-06-23 20:47 UTC, jordigilh commented on flotta-agent.spec
> +export CGO_ENABLED=1
I think we could have the flag enabled just for the `-race`. Would have to define it twice though, but then we enable it for just the race package.
Btw... why would it be bad? I thought having it enabled created a statically linked binary.

2022-06-23 20:53 UTC, jordigilh commented on flotta-agent.spec
> +export CGO_ENABLED=1
Ok, enabled only for the `race` build.

2022-06-23 20:57 UTC, eloycoto requested changes

2022-06-23 20:57 UTC, eloycoto commented on flotta-agent.spec
> +* Thu Jun 23 2022 Jordi Gil <jgil@redhat.com> 0.1.0-3
if you wantt to update the release, do the same on the makefile and on the top of the file

2022-06-24 19:28 UTC, eloycoto approved these changes

2022-06-27 07:25 UTC, masayag approved these changes

2022-06-27 07:25 UTC, merged