Adding UT for OS package
project-flotta/flotta-device-worker pull request #88
Opened 2022-02-08 15:43 UTC by bardielle

2022-02-10 08:50 UTC, jakub-dzon commented
@bardielle - please fix the build failures.

2022-02-10 12:05 UTC, jakub-dzon requested changes

2022-02-13 16:12 UTC, masayag requested changes

2022-02-13 16:12 UTC, masayag commented on internal/os/os.go
> +func NewOS(gracefulRebootChannel chan struct{}, osExecCommands OsExecCommands) *OS {
As mentioned earlier, we can skip the requirement for a second argument and initialize OsExecCommands in this method.

2022-02-13 16:12 UTC, masayag commented on internal/os/os.go
> +		if err != nil{
nit: should be space between nil and {

2022-02-13 16:12 UTC, masayag commented on internal/os/os_exec_commands.go
> +type osExecCommandsStruct struct {}
IINW the suffix `Struct` seems redundant. Can `osExecCommands` be used?

2022-02-13 16:12 UTC, masayag commented on internal/os/os_test.go
> +
can we set the number of calls to the expected amount instead of `AnyTimes`?

2022-02-14 06:46 UTC, bardielle commented on internal/os/os.go
> +	OsExecCommands                  OsExecCommands
But that's the way I can mock the functions in OsExecCommands

2022-02-14 07:03 UTC, masayag approved these changes

2022-02-14 07:05 UTC, masayag commented on internal/os/os_test.go
> +			upgradeStatusBeforeAfterUpdate := deviceOS.GetUpgradeStatus()
s/upgradeStatusBeforeAfterUpdate/upgradeStatusAfterUpdate ?

2022-02-14 07:07 UTC, masayag commented on internal/os/os_test.go
> +			upgradeStatusBeforeAfterUpdate := deviceOS.GetUpgradeStatus()
s/upgradeStatusBeforeAfterUpdate/upgradeStatusAfterUpdate ?

2022-02-14 08:11 UTC, jakub-dzon approved these changes

2022-02-14 11:17 UTC, merged